name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy & Build on VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            sudo rm -rf /var/www/frontend
            git clone https://github.com/onivahcom/frontend.git /var/www/frontend
            cd /var/www/frontend
            npm install --legacy-peer-deps
            CI=false npm run build
            sudo systemctl reload nginx
